imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig', 'php']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

contentful:
    delivery:
        clients:
            default:
                space: CONTENTFUL_SPACE_ID
                token: CONTENTFUL_SPACE_TOKEN
                cache: true
            products:
                space: ANOTHER_CONTENTFUL_SPACE_ID
                token: ANOTHER_CONTENTFUL_SPACE_TOKEN
                cache: true

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        default_controller: AppBundle:Contentful:view
        persistence:
            orm:
                enabled: true

netgen_content_browser:
    item_types:
        contentful_entry:
            name: item_types.contentful_entry
            preview:
                enabled: true
                template: 'ngcb/contentful_entry.html.twig'
            columns:
                # At least a "name" column must exist
                name:
                    name: columns.name # Will be translated with "ngcb" catalog
                    value_provider: name # Using a built in "name" value provider
                content_type:
                    name: columns.contentful_entry.content_type
                    value_provider: contentful_entry\content_type
                created_at:
                    name: columns.contentful_entry.created_at
                    value_provider: contentful_entry\created_at
                updated_at:
                    name: columns.contentful_entry.updated_at
                    value_provider: contentful_entry\updated_at
            default_columns:
                - name
                - content_type

netgen_block_manager:
    pagelayout: 'base.html.twig'
    items:
        value_types:
            contentful_entry:
                name: 'Contentful entry'
    view:
        item_view:
            api:
                contentful_entry:
                    template: "ngbm/item/contentful_entry.html.twig"
                    match:
                        item\value_type: contentful_entry
            default:
                contentful_entry:
                    template: "ngbm/item/contentful_entry.html.twig"
                    match:
                        item\value_type: contentful_entry
        rule_target_view:
            value:
                contentful_entry:
                    template: "ngbm/layout_resolver/target/value/contentful_entry.html.twig"
                    match:
                        rule_target\type: contentful_entry
                contentful_space:
                    template: "ngbm/layout_resolver/target/value/contentful_space.html.twig"
                    match:
                        rule_target\type: contentful_space
        rule_condition_view:
            value:
                contentful_content_type:
                    template: "ngbm/layout_resolver/condition/value/contentful_content_type.html.twig"
                    match:
                        rule_condition\type: contentful_content_type
    query_types:
        contentful_search:
            name: 'Contentful search'
